/:
  controller: Layout
  action: index

/*:
  controller: Layout
  action: index

/admin/dashboard/index:
  controller: Dashboard
  action: index

/admin/user/index:
  controller: User_Controller
  action: index

/admin/user/insert:
  controller: User_Controller
  action: insert

/admin/user/update:
  controller: User_Controller
  action: update

/admin/user/delete:
  controller: User_Controller
  action: delete

/admin/user/status:
  controller: User_Controller
  action: status

/admin/category/index:
  controller: Category_Controller
  action: index

/admin/category/insert:
  controller: Category_Controller
  action: insert

/admin/category/update:
  controller: Category_Controller
  action: update

/admin/category/delete:
  controller: Category_Controller
  action: delete

/admin/category/status:
  controller: Category_Controller
  action: status

/admin/category/sort:
  controller: Category_Controller
  action: sort

/admin/post/index:
  controller: Post_Controller
  action: index

/admin/post/insert:
  controller: Post_Controller
  action: insert

/admin/post/update:
  controller: Post_Controller
  action: update

/admin/post/delete:
  controller: Post_Controller
  action: delete

/admin/post/status:
  controller: Post_Controller
  action: status

/admin/menu/index:
  controller: Menu_Controller
  action: index

/admin/menu/insert:
  controller: Menu_Controller
  action: insert

/admin/menu/update:
  controller: Menu_Controller
  action: update

/admin/menu/delete:
  controller: Menu_Controller
  action: delete

/admin/menu/status:
  controller: Menu_Controller
  action: status

/admin/menu/sort:
  controller: Menu_Controller
  action: sort

/login:
  controller: Security_Controller
  action: login

/processlogin:
  controller: Security_Controller
  action: processlogin

/logout:
  controller: Security_Controller
  action: logout
